version: '3.7'

volumes:
  data:

services:
  server:
    container_name: currency-converter
    build:
      target: production
    env_file: .env.production
    command: yarn start
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    ports:
      - '$DATABASE_PORT:$DATABASE_PORT'
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - data:/var/lib/postgres
