version: '3.7'

volumes:
  data:

services:
  server:
    container_name: currency-converter
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file: .env
    volumes:
      - ./src:$HOME/$APP_NAME/src
      - ./tsconfig.json:$HOME/$APP_NAME/tsconfig.json
    ports:
      - '$PORT:$PORT'
    command: yarn dev
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    ports:
      - '$DATABASE_PORT:$DATABASE_PORT'
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - data:/var/lib/postgres
